allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@vitejs/plugin-react@6.0.5'
  - lucide-react@1.28.0
  - vite@8.2.0
  - '@biomejs/biome@2.5.7'
  - '@biomejs/cli-darwin-arm64@2.5.7'
  - '@biomejs/cli-darwin-x64@2.5.7'
  - '@biomejs/cli-linux-arm64-musl@2.5.7'
  - '@biomejs/cli-linux-arm64@2.5.7'
  - '@biomejs/cli-linux-x64-musl@2.5.7'
  - '@biomejs/cli-linux-x64@2.5.7'
  - '@biomejs/cli-win32-arm64@2.5.7'
  - '@biomejs/cli-win32-x64@2.5.7'
  - zustand@5.0.15

overrides:
  dompurify: "^3.4.12"
